In [5]:
import pandas as pd
import numpy as np

# 엑셀 파일에서 모든 시트를 불러옴
df = pd.read_excel('2020 수업시간표 - pdf 변환.xlsx', sheet_name=None)
df

{'Table 1':      영역구분            교과목명      학수번호  수강반\n번호  학점  이론  실습                  교수명  \
 0     NaN  English/Zone영어  ZTA10001        1   4   0  10    이석광(인문대학 영어영문학과 )
 1     NaN           대학영어1  ZTA10002        1   2   2   0    구승본(인문대학 영어영문학과 )
 2     NaN           대학영어1  ZTA10002        2   2   2   0    이정화(인문대학 영어영문학과 )
 3     NaN           대학영어1  ZTA10002        3   2   2   0     이희정(사범대학 영어교육과 )
 4     NaN           대학영어1  ZTA10002        4   2   2   0     박귀숙(사범대학 영어교육과 )
 ..    ...             ...       ...      ...  ..  ..  ..                  ...
 167   NaN         영어읽기와토론  ZTA20007        2   2   2   0     박경연(사범대학 영어교육과 )
 168   NaN         영어읽기와토론  ZTA20007        3   2   2   0    추지형(인문대학 영어영문학과 )
 169   NaN        컴퓨팅사고와코딩  ZTA20008        1   2   1   1  김동근(자연과학대학 컴퓨터과학과 )
 170   NaN        컴퓨팅사고와코딩  ZTA20008        2   2   1   1  김동근(자연과학대학 컴퓨터과학과 )
 171   NaN        컴퓨팅사고와코딩  ZTA20008        3   2   1   1  박은경(자연과학대학 컴퓨터과학과 )

                                               강의시간/강의실          비고
 0    월11, 12, 13, 화11, 12, 13, 수11, 12, 13, 목11, 12...         NaN
 1                                     수5, 6 [024-0241]    경제1, 사회1
 2                                     월8, 9 [024-0225]  사회복지1, 행정1
 3                                     월2, 3 [024-0141]  심리1, 정치외교1
 4                                     화6, 7 [024-0241]   건축도시토목1-1
 ..                                                 ...         ...
 167                                   금2, 3 [024-0127]         NaN
 168                                   목1, 2 [024-0125]         NaN
 169                                   화3, 4 [102-0204]         NaN
 170                                   수5, 6 [102-0204]         NaN
 171                                   목3, 4 [102-0204]         NaN

 [172 rows x 10 columns],
 'Table 2':       영역구분                    교과목명      학수번호  수강반\n번호  학점  이론  실습  \
 0    문학과문화                TV드라마의이해  ZIA10001        1   2   2   0
 1    문학과문화                고사와성어의탐구  ZIA10002        1   2   2   0
 2    문학과문화                고사와성어의탐구  ZIA10002        2   2   2   0
 3    문학과문화              그리스로마신화의이해  ZIA10004        1   2   2   0
 4    문학과문화              그리스로마신화의이해  ZIA10004      999   2   2   0
 ..     ...                     ...       ...      ...  ..  ..  ..
 136  예술과체육  피트니스스포츠(요가,웨이트트레이닝,GX)  ZIA60028        4   1   0   2
 137  예술과체육  피트니스스포츠(요가,웨이트트레이닝,GX)  ZIA60028        5   1   0   2
 138  융복합영역              꿈을비추는네개의거울  ZIA70002        1   2   2   0
 139  융복합영역                  로봇과인문학  ZIA70003        1   2   2   0
 140  융복합영역                    예술과법  ZIA70004        1   3   3   0

                        교수명              강의시간/강의실             비고
 0         홍상우(인문대학 러시아학과 )      수2, 3 [024-0245]  혼합형(블렌디드) 이러닝
 1            강사미정(경상대학   )      월8, 9 [024-0258]            NaN
 2            강사미정(경상대학   )      목1, 2 [024-0271]            NaN
 3        이영석(인문대학 독어독문학과 )      목3, 4 [024-0160]            NaN
 4        이영석(인문대학 독어독문학과 )               목10 [ ]      본교용_이러닝강좌
 ..                     ...                   ...            ...
 136       이가람(사범대학 체육교육과 )      월8, 9 [005-0108]        웨이트트레이닝
 137       신혜숙(사범대학 체육교육과 )    화10, 11 [303-0214]        GX(RC형)
 138  조대현 외 2명(사범대학 음악교육과 )      월8, 9 [024-0241]            NaN
 139  홍상우 외 1명(인문대학 러시아학과 )      목8, 9 [024-0143]            NaN
 140    신재호 외 1명(법과대학 법학과 )  월5, 수5, 6 [024-0243]            NaN

 [141 rows x 10 columns],
 'Table 3':       영역구분         교과목명      학수번호  수강반\n번호   학점  이론  실습                교수명  \
 0    진로·취업       꿈·미래개척  ZPA10001       11  0.5   0   0  장시광(인문대학 국어국문학과 )
 1    진로·취업       꿈·미래개척  ZPA10001       12  0.5   0   0  정영훈(인문대학 국어국문학과 )
 2    진로·취업       꿈·미래개척  ZPA10001       13  0.5   0   0  박용식(인문대학 국어국문학과 )
 3    진로·취업       꿈·미래개척  ZPA10001       14  0.5   0   0  장만호(인문대학 국어국문학과 )
 4    진로·취업       꿈·미래개척  ZPA10001       16  0.5   0   0  강경호(인문대학 국어국문학과 )
 ..     ...          ...       ...      ...  ...  ..  ..                ...
 733     기타      GNU학습전략  ZPA30027        1  1.0   1   0    강남욱(사범대학 교육학과 )
 734     기타      글로벌환경이슈  ZPA30030        1  2.0   2   0   이동근(공과대학 화학공학과 )
 735     기타      지역사회와봉사  ZPA30031        1  1.0   0   2   하재필(사범대학 체육교육과 )
 736     기타       국제농업교류  ZPA30035        1  2.0   1   3  나채인(대학원 작물생산과학부 )
 737     기타  MATLAB프로그래밍  ZPA30036        1  2.0   1   2  양영일(공과대학 반도체공학과 )

                    강의시간/강의실                     비고
 0                       [ ]                 국어국문학과
 1                       [ ]                 국어국문학과
 2                       [ ]                 국어국문학과
 3                       [ ]                 국어국문학과
 4                       [ ]                 국어국문학과
 ..                      ...                    ...
 733           수4 [303-0417]  학사경고자 연속 2회, 통산 3회 대상
 734        월6, 7 [404-0113]                    NaN
 735        목8, 9 [024-0275]                    NaN
 736  금1, 2, 3, 4 [452-0150]      AIMS 참여학생 전용 강의 /
 737    목8, 9, 10 [405-0322]                    NaN

 [738 rows x 10 columns],
 'Table 4':       영역구분    교과목명      학수번호  수강반\n번호  학점  이론  실습                교수명  \
 0    외국어계열  기초영문독해  ZGA10001        1   3   3   0  이석광(인문대학 영어영문학과 )
 1    외국어계열  기초영문독해  ZGA10001        2   3   3   0  김미정(인문대학 영어영문학과 )
 2    외국어계열  기초영문독해  ZGA10001        3   3   3   0  조은정(인문대학 영어영문학과 )
 3    외국어계열  기초영문독해  ZGA10001        4   3   3   0  조은정(인문대학 영어영문학과 )
 4    외국어계열   기초영문법  ZGA10002        1   3   3   0  이광호(인문대학 영어영문학과 )
 ..     ...     ...       ...      ...  ..  ..  ..                ...
 181   자연계열   화학실험2  ZGA30025       13   1   0   2      교수미정(경상대학   )
 182  선이수교과    기본영어  ZGA40001        1   3   3   0   이희정(사범대학 영어교육과 )
 183  선이수교과   기본물리학  ZGA40002        1   2   2   0      교수미정(경상대학   )
 184  선이수교과    기본수학  ZGA40003        1   2   2   0   문희진(자연과학대학 수학과 )
 185  선이수교과    기본화학  ZGA40004        1   2   2   0      교수미정(경상대학   )

                  강의시간/강의실             비고
 0    월5, 수5, 6 [024-0256]            NaN
 1    월2, 3, 수1 [024-0258]            NaN
 2    월1, 수2, 3 [024-0243]            NaN
 3    수4, 금2, 3 [024-0243]            NaN
 4    월6, 7, 수7 [024-0143]            NaN
 ..                    ...            ...
 181      월2, 3 [352-0436]  수의예1-2, 화학1-2
 182  월1, 수2, 3 [024-0141]     대학영어의 선수과목
 183      금6, 7 [024-0156]      물리학의 선수과목
 184      월2, 3 [024-0171]       수학의 선수과목
 185      화8, 9 [024-0258]       화학의 선수과목

 [186 rows x 10 columns],
 'Table 5':     영역구분          교과목명      학수번호  수강반\n번호  학점  이론  실습               교수명  \
 0    NaN       생활지도및상담  ZCA00002        1   2   2   0   김장회(사범대학 교육학과 )
 1    NaN       생활지도및상담  ZCA00002        2   2   2   0   강남욱(사범대학 교육학과 )
 2    NaN       생활지도및상담  ZCA00002        3   2   2   0   강남욱(사범대학 교육학과 )
 3    NaN       생활지도및상담  ZCA00002        4   2   2   0   주하진(사범대학 교육학과 )
 4    NaN  학교폭력예방및학생의이해  ZCA00003        1   2   2   0   조정미(사범대학 교육학과 )
 5    NaN  학교폭력예방및학생의이해  ZCA00003        2   2   2   0   조정미(사범대학 교육학과 )
 6    NaN  학교폭력예방및학생의이해  ZCA00003        3   2   2   0   강은정(사범대학 교육학과 )
 7    NaN  학교폭력예방및학생의이해  ZCA00003        4   2   2   0   박정숙(사범대학 교육학과 )
 8    NaN       특수교육학개론  ZCA00004        1   2   2   0   강옥화(사범대학 교육학과 )
 9    NaN       특수교육학개론  ZCA00004        2   2   2   0   강옥화(사범대학 교육학과 )
 10   NaN       특수교육학개론  ZCA00004        3   2   2   0   장선경(사범대학 교육학과 )
 11   NaN       특수교육학개론  ZCA00004        4   2   2   0   장선경(사범대학 교육학과 )
 12   NaN         교육학개론  ZCA20001        1   2   2   0   조한익(사범대학 교육학과 )
 13   NaN         교육학개론  ZCA20001        2   2   2   0   송수진(사범대학 교육학과 )
 14   NaN         교육학개론  ZCA20001        3   2   2   0   박정숙(사범대학 교육학과 )
 15   NaN         교육학개론  ZCA20001        4   2   2   0   이현정(사범대학 교육학과 )
 16   NaN      교육철학및교육사  ZCA20002        1   2   2   0   노영숙(사범대학 교육학과 )
 17   NaN      교육철학및교육사  ZCA20002        2   2   2   0   노영숙(사범대학 교육학과 )
 18   NaN      교육철학및교육사  ZCA20002        3   2   2   0   박찬영(사범대학 교육학과 )
 19   NaN      교육철학및교육사  ZCA20002        4   2   2   0   이인철(사범대학 교육학과 )
 20   NaN          교육심리  ZCA20003        1   2   2   0     강사미정(경상대학   )
 21   NaN          교육심리  ZCA20003        2   2   2   0     강사미정(경상대학   )
 22   NaN          교육심리  ZCA20003        3   2   2   0     강사미정(경상대학   )
 23   NaN          교육심리  ZCA20003        4   2   2   0     강사미정(경상대학   )
 24   NaN          교육사회  ZCA20004        1   2   2   0     교수미정(경상대학   )
 25   NaN          교육사회  ZCA20004        2   2   2   0     교수미정(경상대학   )
 26   NaN          교육사회  ZCA20004        3   2   2   0   권근숙(사범대학 교육학과 )
 27   NaN          교육사회  ZCA20004        4   2   2   0   김화숙(사범대학 교육학과 )
 28   NaN     교육과정및교육평가  ZCA30001        1   2   2   0   이문수(사범대학 교육학과 )
 29   NaN     교육과정및교육평가  ZCA30001        2   2   2   0   이문수(사범대학 교육학과 )
 30   NaN     교육과정및교육평가  ZCA30001        3   2   2   0   박외영(사범대학 교육학과 )
 31   NaN     교육과정및교육평가  ZCA30001        4   2   2   0   박외영(사범대학 교육학과 )
 32   NaN     교육방법및교육공학  ZCA30002        1   2   2   0   이동엽(사범대학 교육학과 )
 33   NaN     교육방법및교육공학  ZCA30002        2   2   2   0     강사미정(경상대학   )
 34   NaN     교육방법및교육공학  ZCA30002        3   2   2   0     강사미정(경상대학   )
 35   NaN     교육방법및교육공학  ZCA30002        4   2   2   0     강사미정(경상대학   )
 36   NaN     교육행정및교육경영  ZCA40001        1   2   2   0   주영효(사범대학 교육학과 )
 37   NaN     교육행정및교육경영  ZCA40001        2   2   2   0   주영효(사범대학 교육학과 )
 38   NaN     교육행정및교육경영  ZCA40001        3   2   2   0   정현태(사범대학 교육학과 )
 39   NaN     교육행정및교육경영  ZCA40001        4   2   2   0   정현태(사범대학 교육학과 )
 40   NaN          교직실무  ZCA40030        1   2   2   0   이현정(사범대학 교육학과 )
 41   NaN          교직실무  ZCA40030        2   2   2   0   이현정(사범대학 교육학과 )
 42   NaN          교직실무  ZCA40030        3   2   2   0  정찬기오(사범대학 교육학과 )
 43   NaN          교직실무  ZCA40030        4   2   2   0     강사미정(경상대학   )

             강의시간/강의실  비고
 0   수2, 3 [024-0225] NaN
 1   목6, 7 [303-0417] NaN
 2   목8, 9 [303-0417] NaN
 3   목6, 7 [301-0424] NaN
 4   화3, 4 [301-0423] NaN
 5   수2, 3 [301-0423] NaN
 6   화1, 2 [301-0424] NaN
 7   월8, 9 [301-0430] NaN
 8   금6, 7 [301-0430] NaN
 9   목1, 2 [301-0424] NaN
 10  월2, 3 [301-0424] NaN
 11  수2, 3 [301-0430] NaN
 12  월2, 3 [301-0430] NaN
 13  수2, 3 [303-0717] NaN
 14  월6, 7 [303-0717] NaN
 15  목8, 9 [301-0424] NaN
 16  화8, 9 [301-0430] NaN
 17  수2, 3 [301-0424] NaN
 18  목3, 4 [303-0717] NaN
 19  화8, 9 [024-0225] NaN
 20  목1, 2 [303-0717] NaN
 21  월2, 3 [303-0717] NaN
 22  수7, 8 [303-0717] NaN
 23  금2, 3 [303-0417] NaN
 24  수5, 6 [301-0424] NaN
 25  목3, 4 [301-0423] NaN
 26  월6, 7 [301-0424] NaN
 27  목6, 7 [301-0430] NaN
 28  화3, 4 [301-0424] NaN
 29  목3, 4 [301-0424] NaN
 30  금2, 3 [301-0424] NaN
 31  금4, 5 [301-0424] NaN
 32  목3, 4 [301-0430] NaN
 33  목6, 7 [303-0717] NaN
 34  목8, 9 [303-0717] NaN
 35  화3, 4 [303-0417] NaN
 36  월6, 7 [301-0430] NaN
 37  수5, 6 [301-0430] NaN
 38  화6, 7 [301-0424] NaN
 39  화8, 9 [301-0424] NaN
 40  금6, 7 [301-0424] NaN
 41  금8, 9 [301-0424] NaN
 42  수5, 6 [303-0717] NaN
 43  화8, 9 [303-0717] NaN  ,
 'Table 6':   이수구분 : 일반선택     Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
 0        영역구분           교과목명       학수번호    수강반\n번호         학점         이론
 1         NaN          현장실습3   ZAA90109          1         15          0
 2         NaN        성공취업과전략   ZAA90116          1          2          2
 3         NaN        직무분석과취업   ZAA90117          1          2          2
 4         NaN  군사조직관리및안전사례연구   ZAA90119          1          3          2
 5         NaN    군사조직리더십사례연구   ZAA90121          1          3          2
 6         NaN         전력실무기초   ZAA90122        999          2          2

   Unnamed: 6                      Unnamed: 7                     Unnamed: 8  \
 0         실습                             교수명                       강의시간/강의실
 1         15  이지영(농업생명과학대학 환경산림과학부 환경재료과학전공)                            [ ]
 2          0  이지영(농업생명과학대학 환경산림과학부 환경재료과학전공)               화8, 9 [029-0110]
 3          0  이지영(농업생명과학대학 환경산림과학부 환경재료과학전공)              목8, 9 [035-104-1]
 4          4                            미정()  수2, 3, 금6, 7, 8, 9 [033-0101]
 5          4                            미정()  수2, 3, 금6, 7, 8, 9 [033-0201]
 6          0  이지영(농업생명과학대학 환경산림과학부 환경재료과학전공)                수10 [035-104-1]

                                Unnamed: 9
 0                                      비고
 1                                     NaN
 2                               3, 4학년 대상
 3                               3, 4학년 대상
 4                         ROTC 훈련생 군사학 과목
 5                         ROTC 훈련생 군사학 과목
 6  (KPX 유니온 학점과정 과목)3, 4학년 대상/인재개발원_이러닝강좌  ,
 'Table 7':    이수구분 : 역량교양 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
 0         영역구분       교과목명       학수번호    수강반\n번호         학점         이론
 1          NaN      대학영어1   ZTA10002         71          2          2
 2          NaN      대학영어1   ZTA10002         72          2          2
 3          NaN      대학영어1   ZTA10002         73          2          2
 4          NaN      대학영어2   ZTA10003         71          2          2
 5          NaN      대학영어2   ZTA10003         72          2          2
 6          NaN      대학영어2   ZTA10003         73          2          2
 7          NaN      대학영어2   ZTA10003         74          2          2
 8          NaN      대학영어2   ZTA10003         75          2          2
 9          NaN      대학영어2   ZTA10003         76          2          2
 10         NaN      대학영어2   ZTA10003         77          2          2
 11         NaN      글쓰기기초   ZTA10004         71          2          2
 12         NaN      글쓰기기초   ZTA10004         72          2          2
 13         NaN      글쓰기기초   ZTA10004         73          2          2
 14         NaN      글쓰기기초   ZTA10004         74          2          2
 15         NaN      글쓰기기초   ZTA10004         75          2          2
 16         NaN    수리통계적사고   ZTA20002         71          2          2
 17         NaN      GNU인성   ZTA20003         71          2          2
 18         NaN      글쓰기심화   ZTA20004         71          2          2
 19         NaN      발표와토론   ZTA20005         71          2          2
 20         NaN    영어읽기와토론   ZTA20007         71          2          2
 21         NaN   컴퓨팅사고와코딩   ZTA20008         71          2          1

    Unnamed: 6             Unnamed: 7        Unnamed: 8  \
 0          실습                    교수명          강의시간/강의실
 1           0       강영아(사범대학 영어교육과 )  화6, 7 [011-0302]
 2           0      강연주(인문대학 영어영문학과 )  목3, 4 [011-0301]
 3           0       강영아(사범대학 영어교육과 )  화8, 9 [011-0302]
 4           0   크리스타 엥겔(부속기관 국제어학원 )  화1, 2 [011-0405]
 5           0   크리스타 엥겔(부속기관 국제어학원 )  화8, 9 [011-0405]
 6           0   크리스타 엥겔(부속기관 국제어학원 )  월2, 3 [011-0405]
 7           0   크리스타 엥겔(부속기관 국제어학원 )  목1, 2 [011-0405]
 8           0   크리스타 엥겔(부속기관 국제어학원 )  수5, 6 [011-0405]
 9           0   크리스타 엥겔(부속기관 국제어학원 )  목8, 9 [011-0405]
 10          0   크리스타 엥겔(부속기관 국제어학원 )  금2, 3 [011-0405]
 11          0      이은애(인문대학 국어국문학과 )  월6, 7 [011-0405]
 12          0      정미란(인문대학 국어국문학과 )  수2, 3 [011-0405]
 13          0      백수진(인문대학 국어국문학과 )  목6, 7 [011-0405]
 14          0      강민정(인문대학 국어국문학과 )  화6, 7 [011-0405]
 15          0      조구호(인문대학 국어국문학과 )  목3, 4 [011-0405]
 16          0       정승필(자연과학대학 수학과 )  수2, 3 [011-0301]
 17          0  박문정 외 5명(사범대학 윤리교육과 )  수7, 8 [011-0401]
 18          0      권복순(인문대학 국어국문학과 )  화3, 4 [011-0405]
 19          0      강현주(인문대학 국어국문학과 )  목3, 4 [011-0406]
 20          0      추지형(인문대학 영어영문학과 )  수2, 3 [011-0302]
 21          1    김동근(자연과학대학 컴퓨터과학과 )  월2, 3 [012-0108]

                                      Unnamed: 9
 0                                            비고
 1                                    (해양대)해양식품1
 2                            (해양대)조선해양1, 에너지기계1
 3                            (해양대)기계시스템1, 전체 학년
 4                                    (해양대)수산경영1
 5                                    (해양대)해양경찰1
 6                                    (해양대)정보통신1
 7                                    (해양대)해양토목1
 8                                    (해양대)해양환경1
 9                                    (해양대)전체 학년
 10                                   (해양대)전체 학년
 11                                   (해양대)수산경영1
 12                                   (해양대)해양경찰1
 13                                  (해양대)기계시스템1
 14                                  (해양대)에너지기계1
 15                                   (해양대)해양환경1
 16                                        (해양대)
 17  (해양대)학년별 인원 제한 있음(3~4학년 각 15명, 1~2학년 각 20명)
 18                                        (해양대)
 19                                        (해양대)
 20                                        (해양대)
 21                                        (해양대)  ,
 'Table 8':      영역구분                      교과목명      학수번호  수강반\n번호  학점  이론  실습  \
 0   문학과문화                  TV드라마의이해  ZIA10001       71   2   2   0
 1   문학과문화                그리스로마신화의이해  ZIA10004       71   2   2   0
 2   문학과문화                      말과문화  ZIA10005       71   2   2   0
 3   문학과문화                     문학의이해  ZIA10007       71   2   2   0
 4   문학과문화                   유럽문화의이해  ZIA10013       71   2   2   0
 5   문학과문화                   일본문화의이해  ZIA10014       71   2   2   0
 6   문학과문화               프랑스문화와언어의이해  ZIA10017       71   2   2   0
 7   역사와철학                 동아시아의고전이해  ZIA20003       71   2   2   0
 8   역사와철학                      사회윤리  ZIA20005       71   2   2   0
 9   역사와철학                     인간과윤리  ZIA20010       71   2   2   0
 10  역사와철학                  한국근현대사이해  ZIA20016       71   2   2   0
 11  역사와철학                 한국문화유산의이해  ZIA20017       71   2   2   0
 12  역사와철학                  한국인의역사인식  ZIA20018       71   2   2   0
 13  인간과사회                  나의삶과지방자치  ZIA30005       71   2   2   0
 14  인간과사회                     범죄와인권  ZIA30008       71   2   2   0
 15  인간과사회                      생활법률  ZIA30011       71   2   2   0
 16  인간과사회                      생활법률  ZIA30011       72   2   2   0
 17  생명과환경                      생활원예  ZIA40005       71   2   2   0
 18  과학과기술                      실용수학  ZIA50002       71   2   2   0
 19  과학과기술                   정보통신과미래  ZIA50007       71   2   2   0
 20  과학과기술                     창업과특허  ZIA50008      799   2   2   0
 21  과학과기술                     환경과오염  ZIA50012       71   2   2   0
 22  과학과기술                     환경과오염  ZIA50012       72   2   2   0
 23  예술과체육                     국악의이해  ZIA60005       71   2   2   0
 24  예술과체육                 동계스포츠(스키)  ZIA60008       71   1   0   2
 25  예술과체육                     영화의이해  ZIA60021       71   2   2   0
 26  예술과체육                 축제와공연예술체험  ZIA60023       71   2   2   0
 27  예술과체육  구기(축구,농구,배구,테니스,배드민턴,탁구)  ZIA60027       71   1   0   2
 28  예술과체육    피트니스스포츠(요가,웨이트트레이닝,GX)  ZIA60028       71   1   0   2

                       교수명            강의시간/강의실  \
 0        김용환(인문대학 러시아학과 )    월8, 9 [011-0301]
 1       김충완(인문대학 독어독문학과 )    목6, 7 [011-0104]
 2       이유미(인문대학 국어국문학과 )    화3, 4 [011-0406]
 3       정미진(인문대학 국어국문학과 )    월2, 3 [011-0302]
 4       김충완(인문대학 독어독문학과 )    목8, 9 [011-0104]
 5        강기철(사범대학 일어교육과 )    목8, 9 [011-0404]
 6       김미진(인문대학 불어불문학과 )    화6, 7 [011-0104]
 7           강사미정(경상대학   )    월2, 3 [011-0104]
 8        오희세(사범대학 윤리교육과 )    목3, 4 [011-0401]
 9   이상호 외 3명(사범대학 윤리교육과 )    목8, 9 [011-0401]
 10         정두영(인문대학 사학과 )    수2, 3 [011-0406]
 11         정두영(인문대학 사학과 )    수5, 6 [011-0406]
 12         정두영(인문대학 사학과 )    수7, 8 [011-0406]
 13      오재동(사회과학대학 행정학과 )    목6, 7 [011-0302]
 14       박숙완(부속기관 미래교육원 )    화3, 4 [011-0401]
 15       민상홍(부속기관 미래교육원 )    월6, 7 [011-0104]
 16       민상홍(부속기관 미래교육원 )    월8, 9 [011-0104]
 17          강사미정(경상대학   )    화8, 9 [011-0401]
 18       정승필(자연과학대학 수학과 )    수5, 6 [011-0301]
 19   반태원(해양과학대학 정보통신공학과 )    수2, 3 [011-0104]
 20  정용길(해양과학대학 에너지기계공학과 )  금10, 11 [011-0401]
 21          강사미정(경상대학   )    목1, 2 [011-0104]
 22          강사미정(경상대학   )    목3, 4 [011-0104]
 23       박정련(사범대학 음악교육과 )    화3, 4 [011-0104]
 24          교수미정(경상대학   )    토5, 6 [007-0105]
 25       김용환(인문대학 러시아학과 )    월6, 7 [011-0301]
 26  강경화(연계전공 연계전공 문화콘텐츠학)    화6, 7 [011-0201]
 27       박윤희(사범대학 체육교육과 )   화9, 10 [007-0105]
 28       조혜영(사범대학 체육교육과 )    월6, 7 [007-0105]


In [6]:
combined_df = pd.concat(df.values(), ignore_index=True)
combined_df = combined_df[['교과목명', '교수명', '강의시간/강의실']]
combined_df

,교과목명,교수명,강의시간/강의실
0,English/Zone영어,이석광(인문대학 영어영문학과 ),"월11, 12, 13, 화11, 12, 13, 수11, 12, 13, 목11, 12..."
1,대학영어1,구승본(인문대학 영어영문학과 ),"수5, 6 [024-0241]"
2,대학영어1,이정화(인문대학 영어영문학과 ),"월8, 9 [024-0225]"
3,대학영어1,이희정(사범대학 영어교육과 ),"월2, 3 [024-0141]"
4,대학영어1,박귀숙(사범대학 영어교육과 ),"화6, 7 [024-0241]"
...,...,...,...
1495,NaN,NaN,NaN
1496,NaN,NaN,NaN
1497,NaN,NaN,NaN
1498,NaN,NaN,NaN
1499,NaN,NaN,NaN

In [7]:
# 결측값이 있는 행 삭제
combined_df.dropna(inplace=True)

# 강사/교수미정 학과 제거
combined_df = combined_df[~combined_df['교수명'].str.contains('강사미정')]
combined_df = combined_df[~combined_df['교수명'].str.contains('교수미정')]

# 교수명에서 학과 제거
combined_df['교수명'] = combined_df['교수명'].str.replace(r'\(.*?\)', '', regex=True)
    
# 강의시간과 강의실 데이터 분리
combined_df['강의실'] = combined_df['강의시간/강의실'].str.extract('\[(.*)\]')[0]
combined_df['강의시간/강의실'] = combined_df['강의시간/강의실'].str.replace(r'\[.*?\]', '', regex=True)
combined_df = combined_df.rename(columns={'강의시간/강의실': '강의시간'})

# 값이 없는 행 결측값으로 변경
combined_df['강의시간'].replace(' ', np.nan, inplace=True)
combined_df['강의실'].replace(' ', np.nan, inplace=True)

# 결측값이 있는 행 삭제
combined_df.dropna(inplace=True)

combined_df

           교과목명  교수명       강의시간       강의실
1         대학영어1  구승본     수5, 6   024-0241
2         대학영어1  이정화     월8, 9   024-0225
3         대학영어1  이희정     월2, 3   024-0141
4         대학영어1  박귀숙     화6, 7   024-0241
5         대학영어1  윤수현     화6, 7   024-0243
...         ...  ...        ...       ...
1394      무역창업론  권민석     월2, 3   011-0201
1395   프랜차이즈창업론  김철기  목5, 6, 7   011-0201
1396   지속가능한발전2  최광수     월8, 9   011-0401
1397  지역문화체험과탐방  안영숙     월6, 7   011-0302
1398    GNU학습전략  강남욱        수1   011-0405

[450 rows x 4 columns]

In [8]:
# 저장하기
combined_df.to_excel('2020 수업시간표 - 시트 통합.xlsx', index=False)